// Code generated by tygo. DO NOT EDIT.

//////////
// source: cipher.go

export interface EncryptionRequest {
  plaintext: string;
  isInputHex: boolean;
  nonce: string;
  key: string;
}
export interface EncryptionResp {
  /**
   * Ciphertext is `IV || ciphertext` in hex format.
   */
  output: string;
  loadedLFSR: string;
  loadedNFSR: string;
  initLFSR: string;
  initNFSR: string;
}
export interface DecryptionRequest {
  /**
   * NonceCiphertext is `IV || ciphertext` in hex format.
   */
  ciphertext: string;
  key: string;
}
export interface DecryptionResp {
  output: string;
  nonce: string;
  loadedLFSR: string;
  loadedNFSR: string;
  initLFSR: string;
  initNFSR: string;
}

//////////
// source: key_management.go

export interface WrapKeyRequest {
  key: string;
  password: string;
  ad: string;
  isHex: boolean;
}
export interface UnwrapKeyRequest {
  b64: string;
  passphrase: string;
  ad: string;
  isHex: boolean;
}
export interface WrapKeyResp {
  key: string;
}
export interface UnwrapKeyResp {
  key: string;
}
